name: Generate JSON File List

on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"  # 매 5분마다 실행

jobs:
  generate-json-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List JSON files in data folder
        id: list-files
        run: |
          # KOSPI와 KOSDAQ로 시작하는 파일 목록을 가져옵니다.
          kospi_files=$(ls data/kospi_map_data_*.json | sort -r)
          kosdaq_files=$(ls data/kosdaq_map_data_*.json | sort -r)

          # 날짜별로 파일을 그룹화하기 위한 문자열
          kospi_date_files=""
          kosdaq_date_files=""

          # KOSPI 파일 목록을 반복하며 날짜를 키로 그룹화
          for file in $kospi_files; do
            filename=$(basename "$file")
            date="${filename:15:8}"  # 'kospi_map_data_' 이후의 날짜 추출
            kospi_date_files+="$date:$filename "  # 날짜:파일 이름 형식으로 추가
          done

          # KOSDAQ 파일 목록을 반복하며 날짜를 키로 그룹화
          for file in $kosdaq_files; do
            filename=$(basename "$file")
            date="${filename:16:8}"  # 'kosdaq_map_data_' 이후의 날짜 추출
            kosdaq_date_files+="$date:$filename "  # 날짜:파일 이름 형식으로 추가
          done

          # KOSPI JSON 배열 시작
          echo "[" > kospi.json
          # KOSPI 파일 처리
          for entry in $kospi_date_files; do
            date="${entry%%:*}"  # 날짜 추출
            filename="${entry##*:}"  # 파일 이름 추출
            # 중복된 날짜 확인
            if ! grep -q "\"date\": \"$date\"" kospi.json; then
              echo "  { \"date\": \"$date\", \"files\": [" >> kospi.json
            fi
            echo "    \"$filename\"," >> kospi.json
          done
          # 마지막 쉼표 제거
          sed -i '$ s/,$//' kospi.json
          echo "  ] }," >> kospi.json
          sed -i '$ s/,$//' kospi.json  # 마지막 쉼표 제거
          echo "]" >> kospi.json

          # KOSDAQ JSON 배열 시작
          echo "[" > kosdaq.json
          # KOSDAQ 파일 처리
          for entry in $kosdaq_date_files; do
            date="${entry%%:*}"  # 날짜 추출
            filename="${entry##*:}"  # 파일 이름 추출
            # 중복된 날짜 확인
            if ! grep -q "\"date\": \"$date\"" kosdaq.json; then
              echo "  { \"date\": \"$date\", \"files\": [" >> kosdaq.json
            fi
            echo "    \"$filename\"," >> kosdaq.json
          done
          # 마지막 쉼표 제거
          sed -i '$ s/,$//' kosdaq.json
          echo "  ] }," >> kosdaq.json
          sed -i '$ s/,$//' kosdaq.json  # 마지막 쉼표 제거
          echo "]" >> kosdaq.json

      - name: Check generated JSON files
        run: |
          head kospi.json
          head kosdaq.json

      - name: Save JSON files to treemap
        run: |
          mkdir -p treemap
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
          mv kospi.json "treemap/kospi_json_list_${TIMESTAMP}.json"
          mv kosdaq.json "treemap/kosdaq_json_list_${TIMESTAMP}.json"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # 커밋할 파일이 존재하는지 확인
          if [ -f treemap/kospi_json_list_${TIMESTAMP}.json ] || [ -f treemap/kosdaq_json_list_${TIMESTAMP}.json ]; then
            git add treemap/kospi_json_list_${TIMESTAMP}.json treemap/kosdaq_json_list_${TIMESTAMP}.json
            git commit -m "Update JSON lists for KOSPI and KOSDAQ files" || echo "No changes to commit."
            git push
          else
            echo "No changes to commit."
          fi
