name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests pandas datetime
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run test.py
      run: |
        python "./script/map_market_close.py"

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add data/*.csv
        git commit -m "Update data files"
        git push
      env:
        # GitHub Token for authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
